---
title: "Ex5_contagion_KS"
output: pdf_document
---

# Contagion: Simple vs complex


The concept on contagion in general is that an idea, disease or some other trait can be spread through a population simply by individuals having connections to some person who original has the contagion and passes it along through the group. 

contagion can be split into to groups, simple and complex contagion. Simple contagion is something like a cold that is very easy to catch that only requires you to be connected to one person who gets the cold. As long as everyone in the network is connected by at least one connection eventually everyone in the network will get the cold (as long as there are no sub groups with no connections to other, isolated communities for example) The idea here is that information spreads or "cascades" through a connected group

complex contagion on the other hand is easily explained as an idea or belief that can be spread through a group. the difference between it an simple contagion however is that some threshold must be met for an idea to spread through the network. The threshold is defined as the proportion of an individuals connections who must all believe in the idea in order for them to get on board (become infected with the idea). Another way of thinking about it is that an individual must be exposed many times to an idea in order for them to adopt it. The issue here is that not enough connections between a group and an idea may not be easily spread, more connections and the ideas can spread quickly, too many and again the idea cannot spread as the number of connections who do believe in it become diluted. 

# In an organization

From an organizational perspective it is important to understand complex diffusion as it is the natural way that information will spread through an organization. Depending on the structure of connections in an organization the concept of complex contagion could result in information that is important (and should be spread throughout the group) not being able to break into certain parts of the company. If some group of the company is only weekly connected to the rest of it (below the threshold for contagion) then that information will not be able to break into that group and could have negative impacts. the opposite is also true as discussed above. If some group is very connected, and the idea/behavior/information is only coming from one source (an executive giving direction to a team) then it can be very hard to get the group to buy in as any connection that does exist is diluted by the extreme interconnections.

By understanding the connections of an organization, and knowing how information spreads within it can help us to decide how to change/direct the behavior of a group. This is done by selecting who to approach/get on board initially in order to successfully implement the idea/behavior/information. 

# Understanding threshold

by understanding what the threshold is for the spread of some positive/negative behavior or new idea (learning) we can either take proactive measures to change an organizations structure to be able to either promote its spread or to stop it. For things like learning, this can be done by introducing new ideas to specific key people, or to groups of people. For stopping bad behavior this can be more complex as it involves removing connections (transferring people between department, firing etc...) which can be more complex then introducing ideas in specific places or making new connections as there is the fear that even if we transfer someone to a new department the idea could just spread there instead. 




