---
title: "Final_Report"
output: github_document
---

#Executive Summary

#Introduction 

#Methodology 
Following a series of steps beginning with selecting the data and the characteristic variables, creating advice networks, carrying out calculations of centrality score and application processing time, our consulting team was able to develop a linear regression model including network centrality and demographic attributes, and to provide recommendations to the USPTO for improving the patent application process. 
 
Justification for choices of variables and models 
The two workgroups of examiners selected come from the same technology center to take baseline similarity in terms of the type of work being done into account. Group 161 is focusing on organic compounds patents, whereas 162 is focusing on organic chemistry patents. Because of this, we expect that there will be advice seeking between both groups on cross departmental patent issues. Due to the similar nature of the work, any differences in demographic that appear in the workgroups could be potentially used as explanation for why one group may be able to process applications faster than another. The graphs demonstrate that group 161 has more male than female examiners, while the opposite is observed for group 162, in which the gender diversity is greater and with the greatest difference from the average demographic of the entire USPTO examiners. 
 
Continuing the analysis of groups 161 and 162, this time observing race demographics, it can be observed that both groups are very similar from a race perspective and do not differ much from the average of the USPTO. White and Asian examiners are the most common group, while black and Hispanic examiners make up a smaller minority. These results can be observed in figure 2.  